spring.application.name=employeemanager_jv

# Database Connection
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS;databaseName=dEmployeeManager;integratedSecurity=true;trustServerCertificate=true;
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Note: Do not specify username/password for Windows Authentication
# spring.datasource.username=
# spring.datasource.password=

# JPA/Hibernate Settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.properties.jakarta.persistence.query.timeout=5